# Generated by Django 3.2.9 on 2021-12-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excercise',
            name='desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
